import type { Poem } from './types'

export const POEMS: Poem[] = [
  {
    id: 'after-the-rain-keeps-your-name',
    slug: 'after-the-rain-keeps-your-name',
    title: 'After The Rain Keeps Your Name',
    excerpt: 'The street dries first. The heart takes the longer road.',
    body: `After the rain,\nI walk through the city like it still remembers you.\nStreetlights hold your outline\nin every shallow puddle.\n\nPeople pass.\nTraffic heals itself.\nThe sky acts innocent.\nOnly my chest keeps weather.\n\nIf I call this longing,\nit becomes too simple.\nIf I call it love,\nit still does not explain the silence.\n\nSo I keep walking.\nAnd every dry pavement says\nI survived this,\nwhile every dark reflection says\nnot completely.`,
    moods: ['lonely', 'romantic', 'nostalgic'],
    themes: ['love', 'memory', 'distance'],
    tones: ['melancholic', 'raw'],
    keywords: ['rain', 'city', 'longing', 'silence', 'memory'],
    length: 'medium',
    intensity: 4,
  },
  {
    id: 'small-lamp-in-the-kitchen',
    slug: 'small-lamp-in-the-kitchen',
    title: 'Small Lamp In The Kitchen',
    excerpt: 'Healing rarely arrives like thunder. Sometimes it just leaves the light on.',
    body: `There is a small lamp in the kitchen\nthat refuses drama.\nIt does not cure the night.\nIt only makes a corner of it livable.\n\nTonight,\nthat is enough.\nA chair.\nA glass of water.\nMy breathing not trying to outrun me.\n\nI am learning\nthat healing is not a grand apology from the world.\nIt is a hand on the back.\nIt is soup warming slowly.\nIt is staying.\n\nIt is saying:\nYou do not need to glow.\nYou only need\nto remain.`,
    moods: ['soft', 'hopeful', 'healing'],
    themes: ['home', 'self', 'belonging'],
    tones: ['gentle', 'warm'],
    keywords: ['healing', 'home', 'quiet', 'rest', 'lamp'],
    length: 'medium',
    intensity: 2,
  },
  {
    id: 'night-window-theory',
    slug: 'night-window-theory',
    title: 'Night Window Theory',
    excerpt: 'Some thoughts only trust the dark enough to show their face.',
    body: `At night,\nmy window becomes a second mind.\nThe glass keeps my reflection\nand the dark keeps asking for the truth.\n\nI answer badly.\nI answer in old names,\nin almosts,\nin futures I never learned to hold.\n\nStill,\nthe city hums like a patient machine.\nThe moon does not interrupt.\nAnd for a while,\nI let the silence speak first.\n\nThat is the theory:\nif you stay still long enough,\nyour heart will stop performing\nand begin confessing.`,
    moods: ['dark', 'restless', 'nostalgic'],
    themes: ['night', 'silence', 'self'],
    tones: ['dreamy', 'melancholic'],
    keywords: ['night', 'window', 'thoughts', 'silence', 'confession'],
    length: 'medium',
    intensity: 3,
  },
  {
    id: 'the-distance-between-two-phones',
    slug: 'the-distance-between-two-phones',
    title: 'The Distance Between Two Phones',
    excerpt: 'Some separations are measured in seconds, some in unsent words.',
    body: `Your name still lights my screen\nlike a country I cannot enter.\nI keep the phone face down,\nas if discipline were a border.\n\nWe say we are adults about this.\nWe say distance is ordinary.\nBut there is nothing ordinary\nabout missing someone at 2:14 a.m.\n\nThe room is small.\nThe ache is not.\nEvery vibration becomes hope\nfor half a second.\n\nThen quiet again.\nThat old religion.\nThat digital ghost.\nThat impossible wish\nfor one simple line:\nI am still here.`,
    moods: ['lonely', 'romantic', 'restless'],
    themes: ['distance', 'love', 'waiting'],
    tones: ['raw', 'intense'],
    keywords: ['phone', 'distance', 'waiting', 'ache', 'text'],
    length: 'long',
    intensity: 5,
  },
  {
    id: 'pocketful-of-sunrise',
    slug: 'pocketful-of-sunrise',
    title: 'Pocketful Of Sunrise',
    excerpt: 'Hope is not naive. It is a stubborn craft.',
    body: `I kept a little morning in my pocket\nfor the days that refused to open.\nA thin gold edge.\nA bird practicing courage.\nThe smell of wet leaves agreeing to live.\n\nHope is not loud.\nIt does not kick the door.\nIt waits beside me\nuntil I remember my own name.\n\nThen suddenly,\nI can carry the day again.\nNot perfectly.\nNot beautifully.\nBut forward.\nAnd sometimes\nforward is the brightest thing we do.`,
    moods: ['hopeful', 'healing', 'soft'],
    themes: ['self', 'home', 'belonging'],
    tones: ['warm', 'gentle'],
    keywords: ['hope', 'morning', 'sunrise', 'forward', 'light'],
    length: 'short',
    intensity: 2,
  },
  {
    id: 'museum-of-things-i-never-said',
    slug: 'museum-of-things-i-never-said',
    title: 'Museum Of Things I Never Said',
    excerpt: 'Regret is careful curation.',
    body: `Inside me,\nthere is a museum of unfinished sentences.\nGlass cases full of almost confessions.\nRooms named after the nights\nI chose dignity over honesty.\n\nA soft voice at the entrance says:\nPlease do not touch.\nEverything here is fragile.\nEverything here once breathed.\n\nI walk slowly.\nI know every exhibit by heart.\nThe smile I faked.\nThe apology I delayed.\nThe love I folded too neatly.\n\nIf memory is an artist,\nthen regret is the curator.\nAnd I have been paying admission\nfor years.`,
    moods: ['grief', 'nostalgic', 'dark'],
    themes: ['memory', 'loss', 'silence'],
    tones: ['melancholic', 'intense'],
    keywords: ['regret', 'memory', 'loss', 'silence', 'museum'],
    length: 'long',
    intensity: 5,
  },
  {
    id: 'borrowed-sweater-season',
    slug: 'borrowed-sweater-season',
    title: 'Borrowed Sweater Season',
    excerpt: 'Love can feel like weather made from cloth.',
    body: `Your sweater still knows\nhow to hold my shape.\nThat feels unfair.\nThat feels tender.\nThat feels exactly like October.\n\nThe sleeves fall past my hands,\nas if love were always trying\nto make more room.\nI wear it when the evening cools,\nwhen the street outside softens,\nwhen I want to believe\na person can stay in fabric.\n\nMaybe that is enough for tonight:\nwarmth with a memory in it.\nA small borrowed country.\nA soft place to miss you from.`,
    moods: ['romantic', 'soft', 'nostalgic'],
    themes: ['love', 'memory', 'home'],
    tones: ['warm', 'dreamy'],
    keywords: ['sweater', 'october', 'warmth', 'love', 'memory'],
    length: 'short',
    intensity: 3,
  },
]
